Add transport spacing as configurable property
kbuffington/Georgia pull request #65
Opened 2021-01-17 13:52 UTC by notsigma

After the transport button size property, there is a new one to space the icons.
I tested this from a base install; an existing one, and tried to look through all of the config for base values, and found no problems with this implementation, but I can make whatever changes you want.

Thanks again for this update, spider monkey panel is a significant upgrade performance wise.

2021-01-18 03:14 UTC, kbuffington requested changes
Looks really good, just a few minor changes required.

2021-01-18 03:14 UTC, kbuffington commented on js/georgia-main.js
> +	transportSpacingMenu.addRadioItems(['0px', '3px', '5px (default)', '8px', '15px', '20px', '+2'], pref.transport_buttons_spacing, [-1,3,5,8,15,20,999], (size) => {
I think the options and list should be changed to: 
```
transportSpacingMenu.addRadioItems(['-2', '3px', '5px (default)', '7px', '10px', '15px', '+2'], pref.transport_buttons_spacing, [-1,3,5,7,10,15,999], (size) => {
```

2021-01-18 03:14 UTC, kbuffington commented on js/georgia-main.js
> +		if (pref.show_transport_below) {
We don't need this check as artwork size won't change based on spacing... just if the height of the buttons changes.

2021-01-18 03:14 UTC, kbuffington commented on js/settings.js
> +	transport_buttons_spacing: ['Transport: Button spacing', 5], // size in pixels of the button spacing
Just change the comment to `// size in pixels of the spacing between buttons`

2021-01-18 06:29 UTC, notsigma commented
Thanks for the suggestions; it's better now. Sorry about the extra commits.

2021-01-19 04:24 UTC, merged

2021-01-19 04:25 UTC, kbuffington commented
LGTM, thanks!